name: dns-service
volumes:
  etc-pihole:
  etc-dnsmasq.d:
  unbound:
networks:
  dns:
    driver: bridge
    ipam:
        config:
        - subnet: 172.18.0.0/16
    enable_ipv6: false
services:
  pihole:
    container_name: pihole
    hostname: pihole.home
    image: pihole/pihole:latest
    networks:
      dns:
        ipv4_address: 172.18.0.7
        mac_address: 02:42:0f:4b:32:26
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 85:80/tcp
    environment:
      TZ: Europe/Paris
      WEBPASSWORD: password
      PIHOLE_DNS_: 172.18.0.8#5053
      FTLCONF_LOCAL_IPV4: 172.18.0.7
      FTLCONF_LOCAL_IPV6: ""
      DNSSEC: true
      IPv6: "false"
      WEBUIBOXEDLAYOUT: boxed
      WEBTHEME: dark
      INTERFACE: eth0
      DNSMASQ_LISTENING: single
      FTLCONF_SOCKET_LISTENING: localonly
      FTLCONF_MOZILLA_CANARY: true
      FTLCONF_IGNORE_LOCALHOST: yes
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
  unbound:
    container_name: unbound
    hostname: unbound.home
    image: unbound:1.20
    networks:
      dns:
        ipv4_address: 172.18.0.8
        mac_address: 02:42:AC:17:00:08
    volumes:
      - unbound:/opt/unbound/
    ports:
      - 5053:53/tcp
      - 5053:53/udp
    healthcheck:
      test: [NONE]
    restart: unless-stopped
